language: php
php:
    - 5.4
    - 5.5
    - 5.6
install: composer install
before_script: composer dump-autoload
script:
    - php scripts/testAriette.php
    - php scripts/testIt.php
    - php scripts/testCore.php
