language: php
php:
    - 5.4
    - 5.5
    - 5.6
install: composer install
before_script: composer dump-autoload
script:
    - php scripts/test.php --ariette
    - php scripts/test.php --it
    - php scripts/test.php --core
